---
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  tasks:
    # include tasks
    - include: tasks/base_packages.yml
    - include: tasks/docker.yml
    - include: tasks/kubectl.yml
    # TODO: FIXME: 
    # - include: tasks/postgresql.yml
    # - include: tasks/ruby.yml


  handlers:
    - name: Start services
      apt:
        name: "{{ item }}"
        state: started
      loop:
        - mysql-server
        - postgresql
        - docker
        - redis-server